version: "3.9"

services:

  hotelfahmi:
    image: hotelfahmi
    networks:
      - hotel
    environment:
      CI_ENVIRONMENT: "development"
      app_baseURL   : "http://localhost/"
      database_default_hostname: db
      database_default_database: db_hotel
      database_default_username: hotelfahmi
      database_default_password: "12345"
      database_default_port    : "3306"
      database_default_DBDriver: MySQLi
    ports:
      - "80:80"
    depends_on:
      db:
        condition: service_started

  db:
    image: mariadb:10.7
    networks:
      - hotel
    environment:
      MARIADB_DATABASE: db_hotel
      MARIADB_USER: hotelfahmi
      MARIADB_PASSWORD: "12345"
      MARIADB_ROOT_PASSWORD: "123456789"

networks:
  hotel:
    driver: bridge