version: "3.9"

services:

  server:
    image: hotelfahmi
    networks:
      - hotel
    environment:
      CI_ENVIRONMENT: development
      APP_TYPE      : server
      app_baseURL   : "http://localhost/"
      database_default_hostname: db
      database_default_database: db_hotel
      database_default_username: hotelfahmi
      database_default_password: "12345"
      database_default_port    : "3306"
      database_default_DBDriver: MySQLi
    ports:
      - "8080:80"

  server2:
    image: hotelfahmi
    networks:
      - hotel
    environment:
      CI_ENVIRONMENT: development
      APP_TYPE      : server
      app_baseURL   : "http://localhost/"
      database_default_hostname: db
      database_default_database: db_hotel
      database_default_username: hotelfahmi
      database_default_password: "12345"
      database_default_port    : "3306"
      database_default_DBDriver: MySQLi
    ports:
      - "8081:80"
  
  # sidecar:
  #   image: envoy
  #   networks:
  #     - hotel
  #   environment:
  #     ABCD: abcd
  #   ports:
  #     - "80:80"
  
  # agent:
  #   image: consul
  #   networks:
  #     - hotel
  #   environment:
  #     ABCD: abcd

networks:
  hotel:
    driver: bridge