apiVersion: v1
kind: Service
metadata:
  name: hotel-nodeport
  labels:
    app: hotel
spec:
  type: NodePort
  selector:
    app: hotel-fahmi-server
  ports:
    - port: 80
      targetPort: 80
      nodePort: 32767